import { useEffect } from 'react'
import { toast } from 'sonner'

/**
 * Registers the Workbox service worker (generated by vite-plugin-pwa)
 * and shows a toast when an update is waiting to be activated.
 * Only runs in production builds.
 */
export function useServiceWorkerUpdate() {
  useEffect(() => {
    if (!import.meta.env.PROD) return
    if (!('serviceWorker' in navigator)) return

    // vite-plugin-pwa registers the SW at /sw.js by default
    navigator.serviceWorker.getRegistration().then((reg) => {
      if (!reg) return

      function notifyUpdate() {
        toast('A new version is available.', {
          description: 'Reload the page to get the latest updates.',
          action: {
            label: 'Reload',
            onClick: () => window.location.reload(),
          },
          duration: Infinity,
        })
      }

      // If there is already a waiting worker, notify immediately
      if (reg.waiting) {
        notifyUpdate()
        return
      }

      reg.addEventListener('updatefound', () => {
        const newWorker = reg.installing
        if (!newWorker) return
        newWorker.addEventListener('statechange', () => {
          if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
            notifyUpdate()
          }
        })
      })
    })
  }, [])
}
